# Useful links to make your chat even more beautiful:
# MiniMessages format: https://docs.adventure.kyori.net/minimessage#format
# MiniMessages viewer: https://webui.adventure.kyori.net/
# PAPI placeholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders
# Towny placeholders: https://github.com/TownyAdvanced/Towny/wiki/Placeholders
# Note: PAPI placeholders need to be used like so : <papi:my_placeholder>

# Channel name can be modified
# Channel format can be modified with PAPI's placeholders and MiniMessage syntax.
# MiniMessage syntax is powerful, you can format and add hover/click events easily!
# Channel command can be modified but you'll need to restart your server to get the changes.

# You can use PAPI's placeholders and MiniMessage syntax here too!
format: "<dark_gray><mmo></dark_gray> <town><nation><rank><prefix> <papi:player_displayname> <gray>></gray> <message>"

tags:
  prefix: "<papi:luckperms_prefix>"

  rank: "<papi:lands_land_role>"

  town: "<hover:show_text:'<papi:lands_land_name>\n<papi:lands_land_members> résident.s'><papi:landschat_landtag></hover>"

  nation: "<hover:show_text:'<papi:lands_nation_name>\n<papi:landschat_nationmembers> résident.s'><papi:landschat_nationtag></hover>"

  mmo: "<hover:show_text:'Mineur <papi:lbmmo_miner_level>\nBucheron <papi:lbmmo_lumberjack_level>\nFermier <papi:lbmmo_farmer_level>\nChasseur <papi:lbmmo_hunter_level>'>[<papi:lbmmo_palier_colored>]"

lang:
  err_sender_not_player: "<red>You need to be in-game in order to do this!"

blacklist:
  - "chocolatine"

# MiniMessage, Placeholders and Tags can be used here
misc:
  join_message: "<green>→</green> <rank> <papi:player_displayname>"
  quit_message: "<red>←</red> <rank> <papi:player_displayname>"
  advancement:
    # <advancement_title> and <advancement_description> can be used.
    challenge: "<dark_purple>✽ <papi:player_displayname> has made the advancement <bold><hover:show_text:'<dark_purple><advancement_description>'><advancement_title>"
    goal: "<gold>✸ <papi:player_displayname> has made the advancement <bold><hover:show_text:'<gold><advancement_description>'><advancement_title>"
    task: "<yellow>✦ <papi:player_displayname> has made the advancement <bold><hover:show_text:'<yellow><advancement_description>'><advancement_title>"